### ISSUE TITLE
Chain ID not supported when deploying to Sepolia

### ISSUE THREAD

**Issue by aquanow-alex** [fireblocks/hardhat-fireblocks#9]
Trying to deploy to Sepolia testnet, using the Hardhat and Fireblocks plugin but running into this error: 

hardhat: v2.14.0
@fireblocks/hardhat-fireblocks: v1.2.1

hardhat.config.js
<img width="533" alt="Screenshot 2023-05-07 at 1 09 11 PM" src="https://user-images.githubusercontent.com/113141657/236658890-f59030de-1d21-4b60-a81e-b975e17a222a.png">

`Error: Unsupported chain id: 0xaa36a7.
Supported chains ids: 1, 3, 4, 5, 10, 19, 30, 31, 42, 56, 69, 97, 137, 250, 1284, 1285, 2020, 42161, 42220, 43113, 43114, 44787, 62320, 80001, 421611, MAINNET, ROPSTEN, KOVAN, GOERLI, RINKEBY, BSC, BSC_TEST, POLYGON, POLYGON_TEST, AVALANCHE, AVALANCHE_TEST, MOONRIVER, MOONBEAM, SONGBIRD, ARBITRUM, ARBITRUM_RIN, FANTOM, RSK, RSK_TEST, CELO, CELO_BAK, CELO_ALF, OPTIMISM, OPTIMISM_KOVAN, RONIN
If you're using a private blockchain, you can specify the blockchain's Fireblocks Asset ID via the "assetId" config param.
    at FireblocksWeb3Provider.populateAssetAndChainId (/Users/user_name/Desktop/projects/project_name/node_modules/@fireblocks/fireblocks-web3-provider/src/provider.ts:146:20)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at FireblocksWeb3Provider.populateAccounts (/Users/user_name/Desktop/projects/project_name/node_modules/@fireblocks/fireblocks-web3-provider/src/provider.ts:162:5)`

**Comment by aquanow-alex** [comment]
Dug a little deeper, it looks like Fireblocks Web3 Provider has not integrated the mappings for sepolia yet...

**Comment by aquanow-alex** [comment]
https://github.com/fireblocks/fireblocks-web3-provider/pull/10

PR for fix on other repo

**Comment by orenyomtov** [comment]
Your PR is really appreciated, it was merged, and version [1.2.2](https://github.com/fireblocks/hardhat-fireblocks/releases/tag/v1.2.2) should have Sepolia supported

**Comment by aquanow-alex** [comment]
No problem!
